<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("keywords", "смесительная система СЗР, растворный узел СЗР, смеситель СЗР, дозатор гербицидов, оборудование для производства растворов  СЗР, растворный узел пестицидов, растворный узел удобрений, мобильный растворный узел, стационарный растворный узел, производство растворов СЗР, оборудование для производства КАС 32, смесительная система КАС 32, растворный узел КАС 32, оборудование для производства ЖКУ, смесительная система ЖКУ, растворный узел ЖКУ");
$APPLICATION->SetPageProperty("description", "Стационарный растворный узел СЗР. Оборудование для производства растворов СЗР в автоматическом режиме  с ведением  отчетности и синхронизацией данный с ГИС системами и системами учета 1С");
$APPLICATION->SetPageProperty("title", "Проекты NPK-PRO");

$APPLICATION->SetTitle("Растворный узел СЗР");

?><?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"projects", 
	array(
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"ALLOW_LINK_REVIEWS" => "N",
		"ALLOW_LINK_SERVICES" => "Y",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CATEGORY_CODE" => "",
		"CATEGORY_IBLOCK" => "",
		"CATEGORY_ITEMS_COUNT" => "",
		"CHECK_DATES" => "Y",
		"CONSENT_URL" => "/company/consent/",
		"DESCRIPTION_DETAIL_PROPERTIES" => array(
			0 => "PROPERTY_SCOPE",
			1 => "PROPERTY_DATE",
			2 => "PROPERTY_AUTHOR",
			3 => "PROPERTY_SITE",
		),
		"DETAIL_ACTIVE_DATE_FORMAT" => "j F Y",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => "",
		"DETAIL_LAZYLOAD_USE" => "N",
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "OBJECTIVE",
			1 => "SERVICES",
			2 => "SOLUTION_BEGIN",
			3 => "SOLUTION_END",
			4 => "",
		),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_URL_REVIEWS" => "",
		"DETAIL_URL_SERVICES" => "",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_FORM_ASK" => "Y",
		"DISPLAY_FORM_ORDER" => "Y",
		"DISPLAY_LIST_TAB_ALL" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FILE_404" => "/404.php",
		"FILTER_FIELD_CODE" => "",
		"FILTER_NAME" => "",
		"FILTER_PROPERTY_CODE" => "",
		"FORM_ASK" => "5",
		"FORM_ORDER" => "4",
		"FORUM_ID" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "30",
		"IBLOCK_ID_REVIEWS" => "",
		"IBLOCK_ID_SERVICES" => "16",
		"IBLOCK_TYPE" => "content",
		"IBLOCK_TYPE_REVIEWS" => "",
		"IBLOCK_TYPE_SERVICES" => "catalogs",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => "",
		"LIST_LAZYLOAD_USE" => "N",
		"LIST_PROPERTY_CODE" => array(
			0 => "OBJECTIVE",
			1 => "SERVICES",
			2 => "SOLUTION_BEGIN",
			3 => "SOLUTION_END",
			4 => "",
		),
		"LIST_TEMPLATE" => ".default",
		"MAX_VOTE" => "",
		"MESSAGES_PER_PAGE" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "50",
		"NUM_DAYS" => "",
		"NUM_NEWS" => "",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Новости",
		"PAGE_URL_REVIEWS" => "",
		"PATH_TO_SMILE" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTY_FORM_ORDER_PROJECT" => "11",
		"PROPERTY_GALLERY" => "GALLERY",
		"PROPERTY_IMAGES" => "PICTURES",
		"PROPERTY_OBJECTIVE" => "OBJECTIVE",
		"PROPERTY_SERVICES" => "SERVICES",
		"PROPERTY_SOLUTION_BEGIN" => "SOLUTION_BEGIN",
		"PROPERTY_SOLUTION_END" => "SOLUTION_END",
		"PROPERTY_SOLUTION_IMAGE" => "SOLUTION_PICTURE",
		"REVIEW_AJAX_POST" => "",
		"SEF_FOLDER" => "/company/projects/",
		"SEF_MODE" => "Y",
		"SETTINGS_USE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_404" => "Y",
		"SHOW_LINK_TO_FORUM" => "",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"URL_TEMPLATES_READ" => "",
		"USE_CAPTCHA" => "",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_REVIEW" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"VOTE_NAMES" => "",
		"YANDEX" => "",
		"COMPONENT_TEMPLATE" => "projects",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_CODE#/",
		)
	),
	false
);?><?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php") ?>